# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6f8b2dd659317a9a01a4f12fef8a7f475243431530830855ef06472d318a6d2fc53a8327a75dbd1f82aa3969c6a9cef013edbb6c89b0aa64015aca53c4f260

test:
  secret_key_base: 3ba3bcc1fb01fab52bbdfcb4f22fb813582e2f9c008e686c604388bf9fa250c337bf063387a02828a19426ba65656747d6b01d896b0f054c8110640eca09fef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
